/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * OnOffIndicator.java
 *
 * Created on Oct 9, 2009, 2:15:58 PM
 */

package gui.app;

import java.awt.Color;

/**
 *
 * @author dept of AEM
 */
public class OnOffIndicator extends javax.swing.JPanel {

    /** Creates new form OnOffIndicator */
    public OnOffIndicator() {
        initComponents();
        
        setState(true);
        
    }

    public void setText(String st){
        label.setText(st);
    }
    public void setState(boolean b){
        if(b){
            setBackground(Color.GREEN);
        }
        else{
            setBackground(Color.RED);
        }
    }
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        label = new javax.swing.JLabel();

        setBackground(java.awt.Color.green);

        label.setBackground(new java.awt.Color(0, 255, 51));
        label.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(label, javax.swing.GroupLayout.DEFAULT_SIZE, 55, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(label, javax.swing.GroupLayout.DEFAULT_SIZE, 25, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel label;
    // End of variables declaration//GEN-END:variables

}
