/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * PanelSurfaces.java
 *
 * Created on Oct 9, 2009, 1:57:25 PM
 */

package gui.app;

/**
 *
 * @author dept of AEM
 */
public class PanelSurfaces extends javax.swing.JPanel {

    private double aileron=0;
    private double elevator=0;
    private double throttle =0;
    private double rudder=0;
    /** Creates new form PanelSurfaces */
    public PanelSurfaces() {
        initComponents();
    }

    public void setAileron(double aileron) {
        this.aileron = aileron;
        sliderAileron.setValue((int)this.aileron);
        String st=""+aileron;
        if(st.length()>6){
            st=st.substring(0,7);
        }

        labelAileron.setText("Aileron: "+st);
    }

    public void setElevator(double elevator) {
        this.elevator = elevator;
        sliderElevator.setValue((int)this.elevator);
        String st=""+elevator;
        if(st.length()>6){
            st=st.substring(0,7);
        }
        labelElevator.setText("Elevetor: "+st);
    }

    public void setRudder(double rudder) {
        this.rudder = rudder;
        sliderRudder.setValue((int)this.rudder);
        String st=""+rudder;
        if(st.length()>6){
            st=st.substring(0,7);
        }

        labelRudder.setText("Rudder: "+st);
    }

    

    public void setThrottle(double throttle) {
        this.throttle = throttle;
        sliderThrottle.setValue((int)this.throttle);
        String st=""+throttle;
        if(st.length()>6){
            st=st.substring(0,7);
        }

        labelThrottle.setText("Throttle: "+st);
    }

    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        sliderAileron = new javax.swing.JSlider();
        sliderRudder = new javax.swing.JSlider();
        sliderElevator = new javax.swing.JSlider();
        sliderThrottle = new javax.swing.JSlider();
        labelAileron = new javax.swing.JLabel();
        labelRudder = new javax.swing.JLabel();
        labelElevator = new javax.swing.JLabel();
        labelThrottle = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));

        sliderAileron.setBackground(new java.awt.Color(255, 255, 255));
        sliderAileron.setMaximum(25);
        sliderAileron.setMinimum(-25);
        sliderAileron.setValue(0);
        sliderAileron.setEnabled(false);

        sliderRudder.setBackground(new java.awt.Color(255, 255, 255));
        sliderRudder.setMaximum(25);
        sliderRudder.setMinimum(-25);
        sliderRudder.setValue(0);
        sliderRudder.setEnabled(false);

        sliderElevator.setBackground(new java.awt.Color(255, 255, 255));
        sliderElevator.setMajorTickSpacing(-25);
        sliderElevator.setMaximum(25);
        sliderElevator.setMinimum(-25);
        sliderElevator.setValue(0);
        sliderElevator.setEnabled(false);

        sliderThrottle.setBackground(new java.awt.Color(255, 255, 255));
        sliderThrottle.setMajorTickSpacing(-25);
        sliderThrottle.setValue(0);
        sliderThrottle.setEnabled(false);

        labelAileron.setBackground(new java.awt.Color(255, 255, 255));
        labelAileron.setText("Aileron: 0");

        labelRudder.setBackground(new java.awt.Color(255, 255, 255));
        labelRudder.setText("Rudder: 0");

        labelElevator.setBackground(new java.awt.Color(255, 255, 255));
        labelElevator.setText("Elevator: 0");

        labelThrottle.setBackground(new java.awt.Color(255, 255, 255));
        labelThrottle.setText("Throttle: 0");

        jLabel5.setBackground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("-25");

        jLabel6.setBackground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("25");

        jLabel7.setBackground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("25");

        jLabel8.setBackground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("25");

        jLabel9.setBackground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("100");

        jLabel10.setBackground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("-25");

        jLabel12.setBackground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("0");

        jLabel11.setBackground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("-25");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelAileron, javax.swing.GroupLayout.DEFAULT_SIZE, 77, Short.MAX_VALUE)
                    .addComponent(labelRudder, javax.swing.GroupLayout.DEFAULT_SIZE, 77, Short.MAX_VALUE)
                    .addComponent(labelElevator, javax.swing.GroupLayout.DEFAULT_SIZE, 77, Short.MAX_VALUE)
                    .addComponent(labelThrottle, javax.swing.GroupLayout.DEFAULT_SIZE, 77, Short.MAX_VALUE))
                .addGap(51, 51, 51)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, 16, Short.MAX_VALUE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(sliderThrottle, javax.swing.GroupLayout.DEFAULT_SIZE, 207, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(sliderElevator, javax.swing.GroupLayout.DEFAULT_SIZE, 207, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, 22, Short.MAX_VALUE)
                        .addGap(6, 6, 6))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(sliderRudder, javax.swing.GroupLayout.DEFAULT_SIZE, 207, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, 22, Short.MAX_VALUE)
                        .addGap(6, 6, 6))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(sliderAileron, javax.swing.GroupLayout.DEFAULT_SIZE, 207, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 22, Short.MAX_VALUE)
                        .addGap(6, 6, 6))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(11, 11, 11))
                            .addComponent(sliderAileron, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 25, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(sliderRudder, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(11, 11, 11))
                            .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, 25, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(sliderElevator, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(11, 11, 11))
                            .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, 25, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(11, 11, 11))
                            .addComponent(sliderThrottle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, 25, Short.MAX_VALUE))
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(labelAileron, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(17, 17, 17)
                        .addComponent(labelRudder, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(17, 17, 17)
                        .addComponent(labelElevator, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(17, 17, 17)
                        .addComponent(labelThrottle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(22, 22, 22))))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel labelAileron;
    private javax.swing.JLabel labelElevator;
    private javax.swing.JLabel labelRudder;
    private javax.swing.JLabel labelThrottle;
    private javax.swing.JSlider sliderAileron;
    private javax.swing.JSlider sliderElevator;
    private javax.swing.JSlider sliderRudder;
    private javax.swing.JSlider sliderThrottle;
    // End of variables declaration//GEN-END:variables

}
