/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * PanelWWSettings.java
 *
 * Created on Dec 13, 2009, 6:47:33 PM
 */

package wwj.gui;

/**
 *
 * @author david
 */
public class PanelWWSettings extends javax.swing.JPanel {

    private AppWW appWW;
    /** Creates new form PanelWWSettings */
    public PanelWWSettings() {
        initComponents();
    }
    public void setParent(AppWW _appWW){
        appWW=_appWW;
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonResize = new javax.swing.JButton();
        checkBoxWW = new javax.swing.JCheckBox();
        textOffset = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(254, 254, 254));

        buttonResize.setBackground(new java.awt.Color(73, 68, 103));
        buttonResize.setForeground(new java.awt.Color(254, 254, 254));
        buttonResize.setText("Resize");
        buttonResize.setEnabled(false);
        buttonResize.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonResizeActionPerformed(evt);
            }
        });

        checkBoxWW.setText("World wind enable");
        checkBoxWW.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkBoxWWActionPerformed(evt);
            }
        });

        textOffset.setText("10000");

        jLabel1.setText("Altitude offset");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(checkBoxWW)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(textOffset)
                            .addComponent(jLabel1))
                        .addGap(18, 18, 18)
                        .addComponent(buttonResize, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(162, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(checkBoxWW)
                .addGap(7, 7, 7)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(buttonResize, 0, 0, Short.MAX_VALUE)
                    .addComponent(textOffset))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void buttonResizeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonResizeActionPerformed
        // TODO add your handling code here:
        resize();
    }//GEN-LAST:event_buttonResizeActionPerformed

    private void checkBoxWWActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkBoxWWActionPerformed
        // TODO add your handling code here:
        setWW();
        
    }//GEN-LAST:event_checkBoxWWActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonResize;
    private javax.swing.JCheckBox checkBoxWW;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField textOffset;
    // End of variables declaration//GEN-END:variables

    private void setWW() {
        appWW.setWW(checkBoxWW.isSelected(), Double.parseDouble(textOffset.getText()));
        buttonResize.setEnabled(checkBoxWW.isSelected());
    }

    private void resize() {

        appWW.reSizeView(Double.parseDouble(textOffset.getText()));

    }



}
